Execute events trought adhoc task.
emmarichardson/local_autogroup pull request #54
Opened 2024-06-17 20:09 UTC by ojnadjarm

Added a new setting to enable a feature instead of executing the event handler live, doing it trought an adhoc task.
Added some unit tests.
Added the option to add group with separed coma to an user profile field 'Group1, gruop2, group3'

2024-06-17 21:16 UTC, ak4t0sh commented
Hi @ojnadjarm
I remember discussing about this with someone from HQ last year, it's a real pleasure to see this PR landing :)
At first sight it seems OK but I'll try to do a proper review and some tests later.
ping @emmarichardson if you have some time to tests it too

2024-07-19 15:24 UTC, emmarichardson commented
@ak4t0sh have you had a chance to look at this?

2024-07-22 10:38 UTC, ak4t0sh requested changes

2024-07-22 10:38 UTC, ak4t0sh commented on classes/task/process_event.php
> +        return get_string('process_event', 'tool_objectfs_lmcs');
you are using string from en external plugin.
It should be defined in local_autogroup.

2024-07-22 10:38 UTC, ak4t0sh commented on tests/local_autogroup_lib_test.php
> + * @author     David Saylor <david@mylearningconsultants.com>
I do not think this informations are accurate.

2024-07-22 10:42 UTC, ak4t0sh commented
Hi @emmarichardson
Again Thanks @ojnadjarm for this PR !
Technically the only "blocker" is the use of a string from an external plugin.

My only "concern" is about the multiple groups generation based on comma separated values.
I think that is a great and must have feature but it could have unwanted behaviour for sites already using autogroups.
Indeed currently if users have groups linked to custom fields containing comma it create groups with comma in their names
If we merge this it would create multiple groups.

For instance "Tester,Developer,Ops"
Currently : 1 groups "Tester,Developer,Administrator" 
After merge : 3 groups. "Tester", "Developer" and "Administrator"

So IMHO to prevent this it should be an option (with a default at site level) to define when adding an autogroup into a course.

Also @ojnadjarm could you "clean" your git history please ?  
Ideally could you keep only 2 commits - one for the multiple groups on comma separated value feature and the other for the adhoc task - please ?

TIA

2024-07-22 11:46 UTC, emmarichardson commented
@ak4t0sh  The multiple groups from comma separated values has already been implemented in a previous PR...it has been in use for some time now.  So far no-one has complained..

2024-07-22 13:14 UTC, ak4t0sh commented
Oh thanks for the reminder @emmarichardson  you are right I totally forgot about it.
From what I can see in #49 a new sort_module (`local_autogroup\sort_module\user_info_field_multivalue`) has been introduced to handle multiple values field which do not cause any side effect for existing installations.  
But this PR do not use this system and use an hardcoded comma to create multiple groups in `local_autogroup\sort_module\user_info_field` which can have side effects for existing autogroup instances.
So IMO this part should be removed as it's already implemented

2024-07-22 13:15 UTC, emmarichardson commented
Thank you. That helps.

Emma Richardson
Distance Learning Coordinator
719-771-4022
Need to visit? Click below to schedule an appointment.
https://calendar.app.google/vy9C7FEp2GCNQrbE7

On Mon, Jul 22, 2024, 7:14 AM Arnaud Trouvé ***@***.***>
wrote:

> Oh thanks for the reminder @emmarichardson
> <https://github.com/emmarichardson> you are right I totally forgot about
> it.
> From what I can see in #49
> <https://github.com/emmarichardson/local_autogroup/pull/49> a new
> sort_module (local_autogroup\sort_module\user_info_field_multivalue) has
> been introduced to handle multiple values field which do not cause any side
> effect for existing installations.
> But this PR do not use this system and use an hardcoded comma to create
> multiple groups in local_autogroup\sort_module\user_info_field which can
> have side effects for existing autogroup instances.
> So IMO this part should be removed as it's already implemented
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/emmarichardson/local_autogroup/pull/54#issuecomment-2242932689>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAP3TGOQ3JDMV5WWS3HMRCDZNUAUDAVCNFSM6AAAAABJOVDNPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBSHEZTENRYHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-22 17:45 UTC, ojnadjarm commented
Hi I have clean up the commitsand the requested changes, let me know what you think :D

2024-07-29 08:43 UTC, ak4t0sh requested changes

2024-07-29 08:43 UTC, ak4t0sh commented on classes/event_handler.php
> +            strstr($data->otherother->component, 'autogroup')
you are checking if `$data->other`  is an array and then using it as an object ? :thinking:   
Could you keep the array form please ?  
  
Moreover I don't think that `$data->otherother`  exits ;)

2024-07-29 08:47 UTC, ak4t0sh commented
Thanks for the fixes @ojnadjarm ! Almost good to me, could you look at my 2 new feedback please :)

2024-08-23 16:27 UTC, ojnadjarm commented
Hi @ak4t0sh Sorry for the late response. Checking out.

2024-08-23 16:34 UTC, ojnadjarm commented on classes/event_handler.php
> +            strstr($data->otherother->component, 'autogroup')
Hi, when we save the event as a custom_data for the ad-hoc task,  is saved as a json, once you retrieve the event the adhoc task custom data it automatically convert it to an object. So this is now and object, the otherother if a typo fixing it.

2024-09-09 19:32 UTC, ak4t0sh commented
Thanks for your patience @ojnadjarm. Code seems good to me. 
But you have added an extra commit which as nothing to do with this PR. 
Could you remove it please ?

Moreover I have done some quick tests and have some error appearing.

## Testing environment
Moodle 4.4
1 course with 2 autogroups : 1 based on profile field and the other one on custom profile field. Tried with multi values too.
Tests done only by editing user profile.
## Results

### Sync mode (adhoceventhandler disable)
I have the following stack when editing an user profile. (But it works correctly)
```
Exception encountered in event observer '\local_autogroup\event_handler::create_adhoc_task': This ID number is already in use
    line 235 of /local/autogroup/classes/domain/group.php: call to groups_create_group()
    line 535 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\group->create()
    line 448 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\autogroup_set->get_or_create_group_by_idnumber()
    line 138 of /local/autogroup/classes/domain/course.php: call to local_autogroup\domain\autogroup_set->verify_user_group_membership()
    line 159 of /local/autogroup/classes/domain/user.php: call to local_autogroup\domain\course->verify_user_group_membership()
    line 70 of /local/autogroup/classes/usecase/verify_user_group_membership.php: call to local_autogroup\domain\user->verify_user_group_membership()
    line 165 of /local/autogroup/classes/event_handler.php: call to local_autogroup\usecase\verify_user_group_membership->invoke()
    line 347 of /local/autogroup/classes/event_handler.php: call to local_autogroup\event_handler::user_updated()
    line 46 of /local/autogroup/classes/task/process_event.php: call to local_autogroup\event_handler::process_event()
    line 335 of /local/autogroup/classes/event_handler.php: call to local_autogroup\task\process_event->execute()
    line ? of unknownfile: call to local_autogroup\event_handler::create_adhoc_task()
    line 155 of /lib/classes/event/manager.php: call to call_user_func()
    line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
    line 795 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
    line 287 of /user/editadvanced.php: call to core\event\base->trigger()
```
I checked in DB I had a pending adhoc task but non related to this plugin. (moodle notification)

### Async mode (adhoceventhandler enable)
After editing an user profile the following stack appear when running cron for the first time after a change on a user profile...and a faildelay is added to the adhoc task. Then it works as expected on the next run.
```
Execute adhoc task: local_autogroup\task\process_event
Adhoc task id: 54
Adhoc task custom data: {"eventname":"\\core\\event\\user_updated","component":"core","action":"updated","target":"user","objecttable":"user","objectid":"3","crud":"u","edulevel":0,"contextid":23,"contextlevel":30,"contextinstanceid":"3","userid":"2","courseid":0,"relateduserid":"3","anonymous":0,"other":null,"timecreated":1725909338}
... started 20:16:15. Current memory use 3.5 MB.
++ Fields list in snapshot record does not match fields list in 'groups'. Record is missing fields: visibility, participation ++
* line 862 of /lib/classes/event/base.php: call to debugging()
* line 239 of /group/lib.php: call to core\event\base->add_record_snapshot()
* line 213 of /local/autogroup/classes/domain/group.php: call to groups_remove_member()
* line 463 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\group->ensure_user_is_not_member()
* line 138 of /local/autogroup/classes/domain/course.php: call to local_autogroup\domain\autogroup_set->verify_user_group_membership()
* line 159 of /local/autogroup/classes/domain/user.php: call to local_autogroup\domain\course->verify_user_group_membership()
* line 70 of /local/autogroup/classes/usecase/verify_user_group_membership.php: call to local_autogroup\domain\user->verify_user_group_membership()
* line 165 of /local/autogroup/classes/event_handler.php: call to local_autogroup\usecase\verify_user_group_membership->invoke()
* line 347 of /local/autogroup/classes/event_handler.php: call to local_autogroup\event_handler::user_updated()
* line 46 of /local/autogroup/classes/task/process_event.php: call to local_autogroup\event_handler::process_event()
* line 519 of /lib/classes/cron.php: call to local_autogroup\task\process_event->execute()
* line 302 of /lib/classes/cron.php: call to core\cron::run_inner_adhoc_task()
* line 128 of /lib/classes/cron.php: call to core\cron::run_adhoc_tasks()
* line 80 of /admin/cron.php: call to core\cron::run_main_process()
++ Fields list in snapshot record does not match fields list in 'groups'. Record is missing fields: visibility, participation ++
* line 862 of /lib/classes/event/base.php: call to debugging()
* line 239 of /group/lib.php: call to core\event\base->add_record_snapshot()
* line 213 of /local/autogroup/classes/domain/group.php: call to groups_remove_member()
* line 463 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\group->ensure_user_is_not_member()
* line 138 of /local/autogroup/classes/domain/course.php: call to local_autogroup\domain\autogroup_set->verify_user_group_membership()
* line 159 of /local/autogroup/classes/domain/user.php: call to local_autogroup\domain\course->verify_user_group_membership()
* line 70 of /local/autogroup/classes/usecase/verify_user_group_membership.php: call to local_autogroup\domain\user->verify_user_group_membership()
* line 165 of /local/autogroup/classes/event_handler.php: call to local_autogroup\usecase\verify_user_group_membership->invoke()
* line 347 of /local/autogroup/classes/event_handler.php: call to local_autogroup\event_handler::user_updated()
* line 46 of /local/autogroup/classes/task/process_event.php: call to local_autogroup\event_handler::process_event()
* line 519 of /lib/classes/cron.php: call to local_autogroup\task\process_event->execute()
* line 302 of /lib/classes/cron.php: call to core\cron::run_inner_adhoc_task()
* line 128 of /lib/classes/cron.php: call to core\cron::run_adhoc_tasks()
* line 80 of /admin/cron.php: call to core\cron::run_main_process()
... used 87 dbqueries
... used 0.063717126846313 seconds
Adhoc task failed: local_autogroup\task\process_event,This ID number is already in use
Backtrace:
* line 235 of /local/autogroup/classes/domain/group.php: call to groups_create_group()
* line 535 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\group->create()
* line 448 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\autogroup_set->get_or_create_group_by_idnumber()
* line 138 of /local/autogroup/classes/domain/course.php: call to local_autogroup\domain\autogroup_set->verify_user_group_membership()
* line 159 of /local/autogroup/classes/domain/user.php: call to local_autogroup\domain\course->verify_user_group_membership()
* line 70 of /local/autogroup/classes/usecase/verify_user_group_membership.php: call to local_autogroup\domain\user->verify_user_group_membership()
* line 165 of /local/autogroup/classes/event_handler.php: call to local_autogroup\usecase\verify_user_group_membership->invoke()
* line 347 of /local/autogroup/classes/event_handler.php: call to local_autogroup\event_handler::user_updated()
* line 46 of /local/autogroup/classes/task/process_event.php: call to local_autogroup\event_handler::process_event()
* line 519 of /lib/classes/cron.php: call to local_autogroup\task\process_event->execute()
* line 302 of /lib/classes/cron.php: call to core\cron::run_inner_adhoc_task()
* line 128 of /lib/classes/cron.php: call to core\cron::run_adhoc_tasks()
* line 80 of /admin/cron.php: call to core\cron::run_main_process()

Execute adhoc task: local_autogroup\task\process_event
Adhoc task id: 55
Adhoc task custom data: {"eventname" [...]

2025-02-03 18:13 UTC, ojnadjarm commented
Hi @ak4t0sh Sorry I have been very busy, and forgot to coming back to this, I was able to replicate the issues and fix them, whenever you got the time test the changes and let me know if we are good to go, thanks :D

2025-03-27 09:39 UTC, ak4t0sh approved these changes

2025-05-05 19:59 UTC, merged

2025-05-06 14:04 UTC, emmarichardson commented
Hey guys, I messed up.  I went ahead and merged this but am now finding on 4.5 with PGSQL db, the menu item does not appear in the course - can we get that fixed please?   Also, I am now seeing these errors on mariadb: 
Invalid get_string() identifier: 'adhoceventhandler' or component 'local_autogroup'. Perhaps you are missing $string['adhoceventhandler'] = ''; in /var/www/html/local/autogroup/lang/en/local_autogroup.php?
line 355 of /lib/classes/string_manager_standard.php: call to debugging()
line 7013 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 88 of /local/autogroup/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 902 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 8847 of /lib/adminlib.php: call to require()
line 31 of /admin/search.php: call to admin_get_root()

2025-05-06 15:12 UTC, ojnadjarm commented
Hi Sure I'll do it ASAP

2025-05-06 22:47 UTC, emmarichardson commented
Thanks - please pull down the latest version - I made some minor changes today and I am not 100% I was able to get rid of all your code as I was prompted for a setting to use adhoc tasks, which didn't make sense to me as that setting was in the version that I downloaded prior to the merge...